// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Состояние настройки. `blockingActive` намеренно отдельно от `hasRole`:
/// без роли сервис не вызывается вообще, и обещать «блокировка активна» нельзя (ТЗ §18 п. 2).
class SetupStatus {
  SetupStatus({
    required this.hasRole,
    required this.hasCallLog,
    required this.hasContacts,
    required this.hasNotifications,
    required this.blockingEnabled,
    required this.blockingActive,
    required this.enabledRuleCount,
    required this.problems,
    this.lastScreeningAt,
  });

  bool hasRole;

  bool hasCallLog;

  bool hasContacts;

  bool hasNotifications;

  bool blockingEnabled;

  bool blockingActive;

  int enabledRuleCount;

  /// Коды проблем: NO_ROLE, DISABLED_BY_USER, NO_RULES, NO_CALL_LOG, NO_CONTACTS,
  /// NO_NOTIFICATIONS. Строками, а не перечислением, чтобы добавление кода не ломало мост.
  List<String> problems;

  int? lastScreeningAt;

  List<Object?> _toList() {
    return <Object?>[
      hasRole,
      hasCallLog,
      hasContacts,
      hasNotifications,
      blockingEnabled,
      blockingActive,
      enabledRuleCount,
      problems,
      lastScreeningAt,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SetupStatus decode(Object result) {
    result as List<Object?>;
    return SetupStatus(
      hasRole: result[0]! as bool,
      hasCallLog: result[1]! as bool,
      hasContacts: result[2]! as bool,
      hasNotifications: result[3]! as bool,
      blockingEnabled: result[4]! as bool,
      blockingActive: result[5]! as bool,
      enabledRuleCount: result[6]! as int,
      problems: (result[7]! as List<Object?>).cast<String>(),
      lastScreeningAt: result[8] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SetupStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasRole, other.hasRole) &&
        _deepEquals(hasCallLog, other.hasCallLog) &&
        _deepEquals(hasContacts, other.hasContacts) &&
        _deepEquals(hasNotifications, other.hasNotifications) &&
        _deepEquals(blockingEnabled, other.blockingEnabled) &&
        _deepEquals(blockingActive, other.blockingActive) &&
        _deepEquals(enabledRuleCount, other.enabledRuleCount) &&
        _deepEquals(problems, other.problems) &&
        _deepEquals(lastScreeningAt, other.lastScreeningAt);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SetupStatus(hasRole: $hasRole, hasCallLog: $hasCallLog, hasContacts: $hasContacts, hasNotifications: $hasNotifications, blockingEnabled: $blockingEnabled, blockingActive: $blockingActive, enabledRuleCount: $enabledRuleCount, problems: $problems, lastScreeningAt: $lastScreeningAt)';
  }
}

class RuleDto {
  RuleDto({
    required this.id,
    required this.title,
    required this.targetType,
    required this.matchType,
    required this.pattern,
    required this.patternCanonical,
    required this.action,
    required this.orderIndex,
    required this.isEnabled,
    required this.translitVariants,
    required this.matchCount,
    this.regexField,
    this.comment,
    this.lastMatchedAt,
  });

  int id;

  String title;

  String targetType;

  String matchType;

  /// Как ввёл пользователь — это и показывается ему.
  String pattern;

  /// Канонизированный вид: по нему идёт сопоставление. Полезно показать в отладке.
  String patternCanonical;

  String action;

  int orderIndex;

  bool isEnabled;

  bool translitVariants;

  int matchCount;

  String? regexField;

  String? comment;

  int? lastMatchedAt;

  List<Object?> _toList() {
    return <Object?>[
      id,
      title,
      targetType,
      matchType,
      pattern,
      patternCanonical,
      action,
      orderIndex,
      isEnabled,
      translitVariants,
      matchCount,
      regexField,
      comment,
      lastMatchedAt,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RuleDto decode(Object result) {
    result as List<Object?>;
    return RuleDto(
      id: result[0]! as int,
      title: result[1]! as String,
      targetType: result[2]! as String,
      matchType: result[3]! as String,
      pattern: result[4]! as String,
      patternCanonical: result[5]! as String,
      action: result[6]! as String,
      orderIndex: result[7]! as int,
      isEnabled: result[8]! as bool,
      translitVariants: result[9]! as bool,
      matchCount: result[10]! as int,
      regexField: result[11] as String?,
      comment: result[12] as String?,
      lastMatchedAt: result[13] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RuleDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(title, other.title) &&
        _deepEquals(targetType, other.targetType) &&
        _deepEquals(matchType, other.matchType) &&
        _deepEquals(pattern, other.pattern) &&
        _deepEquals(patternCanonical, other.patternCanonical) &&
        _deepEquals(action, other.action) &&
        _deepEquals(orderIndex, other.orderIndex) &&
        _deepEquals(isEnabled, other.isEnabled) &&
        _deepEquals(translitVariants, other.translitVariants) &&
        _deepEquals(matchCount, other.matchCount) &&
        _deepEquals(regexField, other.regexField) &&
        _deepEquals(comment, other.comment) &&
        _deepEquals(lastMatchedAt, other.lastMatchedAt);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RuleDto(id: $id, title: $title, targetType: $targetType, matchType: $matchType, pattern: $pattern, patternCanonical: $patternCanonical, action: $action, orderIndex: $orderIndex, isEnabled: $isEnabled, translitVariants: $translitVariants, matchCount: $matchCount, regexField: $regexField, comment: $comment, lastMatchedAt: $lastMatchedAt)';
  }
}

/// Результат проверки шаблона в редакторе.
class PatternCheckResult {
  PatternCheckResult({
    required this.valid,
    required this.canonical,
    required this.variants,
    required this.variantsTruncated,
    this.error,
  });

  bool valid;

  String canonical;

  /// Что именно правило будет искать. Показывается пользователю: непрозрачное нечёткое
  /// сравнение недопустимо, ложное срабатывание — пропущенный звонок от врача (ТЗ §6.3.2).
  List<String> variants;

  bool variantsTruncated;

  String? error;

  List<Object?> _toList() {
    return <Object?>[valid, canonical, variants, variantsTruncated, error];
  }

  Object encode() {
    return _toList();
  }

  static PatternCheckResult decode(Object result) {
    result as List<Object?>;
    return PatternCheckResult(
      valid: result[0]! as bool,
      canonical: result[1]! as String,
      variants: (result[2]! as List<Object?>).cast<String>(),
      variantsTruncated: result[3]! as bool,
      error: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PatternCheckResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(valid, other.valid) &&
        _deepEquals(canonical, other.canonical) &&
        _deepEquals(variants, other.variants) &&
        _deepEquals(variantsTruncated, other.variantsTruncated) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PatternCheckResult(valid: $valid, canonical: $canonical, variants: $variants, variantsTruncated: $variantsTruncated, error: $error)';
  }
}

class SaveRuleResult {
  SaveRuleResult({
    required this.saved,
    required this.id,
    required this.variants,
    required this.variantsTruncated,
    this.error,
  });

  bool saved;

  int id;

  List<String> variants;

  bool variantsTruncated;

  String? error;

  List<Object?> _toList() {
    return <Object?>[saved, id, variants, variantsTruncated, error];
  }

  Object encode() {
    return _toList();
  }

  static SaveRuleResult decode(Object result) {
    result as List<Object?>;
    return SaveRuleResult(
      saved: result[0]! as bool,
      id: result[1]! as int,
      variants: (result[2]! as List<Object?>).cast<String>(),
      variantsTruncated: result[3]! as bool,
      error: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SaveRuleResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(saved, other.saved) &&
        _deepEquals(id, other.id) &&
        _deepEquals(variants, other.variants) &&
        _deepEquals(variantsTruncated, other.variantsTruncated) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SaveRuleResult(saved: $saved, id: $id, variants: $variants, variantsTruncated: $variantsTruncated, error: $error)';
  }
}

class JournalItemDto {
  JournalItemDto({
    required this.id,
    required this.occurredAt,
    required this.rawNumber,
    required this.nameSource,
    required this.action,
    required this.reason,
    required this.latencyMs,
    required this.blockedByUs,
    required this.hadSignature,
    this.e164,
    this.nameRaw,
    this.matchedRuleId,
    this.matchedRuleTitle,
  });

  int id;

  int occurredAt;

  String rawNumber;

  String nameSource;

  String action;

  String reason;

  int latencyMs;

  bool blockedByUs;

  bool hadSignature;

  String? e164;

  String? nameRaw;

  int? matchedRuleId;

  String? matchedRuleTitle;

  List<Object?> _toList() {
    return <Object?>[
      id,
      occurredAt,
      rawNumber,
      nameSource,
      action,
      reason,
      latencyMs,
      blockedByUs,
      hadSignature,
      e164,
      nameRaw,
      matchedRuleId,
      matchedRuleTitle,
    ];
  }

  Object encode() {
    return _toList();
  }

  static JournalItemDto decode(Object result) {
    result as List<Object?>;
    return JournalItemDto(
      id: result[0]! as int,
      occurredAt: result[1]! as int,
      rawNumber: result[2]! as String,
      nameSource: result[3]! as String,
      action: result[4]! as String,
      reason: result[5]! as String,
      latencyMs: result[6]! as int,
      blockedByUs: result[7]! as bool,
      hadSignature: result[8]! as bool,
      e164: result[9] as String?,
      nameRaw: result[10] as String?,
      matchedRuleId: result[11] as int?,
      matchedRuleTitle: result[12] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! JournalItemDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(occurredAt, other.occurredAt) &&
        _deepEquals(rawNumber, other.rawNumber) &&
        _deepEquals(nameSource, other.nameSource) &&
        _deepEquals(action, other.action) &&
        _deepEquals(reason, other.reason) &&
        _deepEquals(latencyMs, other.latencyMs) &&
        _deepEquals(blockedByUs, other.blockedByUs) &&
        _deepEquals(hadSignature, other.hadSignature) &&
        _deepEquals(e164, other.e164) &&
        _deepEquals(nameRaw, other.nameRaw) &&
        _deepEquals(matchedRuleId, other.matchedRuleId) &&
        _deepEquals(matchedRuleTitle, other.matchedRuleTitle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'JournalItemDto(id: $id, occurredAt: $occurredAt, rawNumber: $rawNumber, nameSource: $nameSource, action: $action, reason: $reason, latencyMs: $latencyMs, blockedByUs: $blockedByUs, hadSignature: $hadSignature, e164: $e164, nameRaw: $nameRaw, matchedRuleId: $matchedRuleId, matchedRuleTitle: $matchedRuleTitle)';
  }
}

class JournalPageDto {
  JournalPageDto({
    required this.items,
    required this.hasMore,
    this.nextBeforeTime,
    this.nextBeforeId,
  });

  List<JournalItemDto> items;

  bool hasMore;

  /// Курсор составной: метки времени в миллисекундах совпадают у соседних записей при
  /// пакетной вставке, и курсор по одному полю пропускал бы строки (архитектура §7.3).
  int? nextBeforeTime;

  int? nextBeforeId;

  List<Object?> _toList() {
    return <Object?>[items, hasMore, nextBeforeTime, nextBeforeId];
  }

  Object encode() {
    return _toList();
  }

  static JournalPageDto decode(Object result) {
    result as List<Object?>;
    return JournalPageDto(
      items: (result[0]! as List<Object?>).cast<JournalItemDto>(),
      hasMore: result[1]! as bool,
      nextBeforeTime: result[2] as int?,
      nextBeforeId: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! JournalPageDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(items, other.items) &&
        _deepEquals(hasMore, other.hasMore) &&
        _deepEquals(nextBeforeTime, other.nextBeforeTime) &&
        _deepEquals(nextBeforeId, other.nextBeforeId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'JournalPageDto(items: $items, hasMore: $hasMore, nextBeforeTime: $nextBeforeTime, nextBeforeId: $nextBeforeId)';
  }
}

class SummaryDto {
  SummaryDto({
    required this.blockedToday,
    required this.totalEvents,
    required this.withSignatureLast100,
    required this.checkedLast100,
    this.lastEventAt,
  });

  int blockedToday;

  int totalEvents;

  int withSignatureLast100;

  int checkedLast100;

  int? lastEventAt;

  List<Object?> _toList() {
    return <Object?>[
      blockedToday,
      totalEvents,
      withSignatureLast100,
      checkedLast100,
      lastEventAt,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SummaryDto decode(Object result) {
    result as List<Object?>;
    return SummaryDto(
      blockedToday: result[0]! as int,
      totalEvents: result[1]! as int,
      withSignatureLast100: result[2]! as int,
      checkedLast100: result[3]! as int,
      lastEventAt: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SummaryDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(blockedToday, other.blockedToday) &&
        _deepEquals(totalEvents, other.totalEvents) &&
        _deepEquals(withSignatureLast100, other.withSignatureLast100) &&
        _deepEquals(checkedLast100, other.checkedLast100) &&
        _deepEquals(lastEventAt, other.lastEventAt);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SummaryDto(blockedToday: $blockedToday, totalEvents: $totalEvents, withSignatureLast100: $withSignatureLast100, checkedLast100: $checkedLast100, lastEventAt: $lastEventAt)';
  }
}

class PreviewDto {
  PreviewDto({required this.count, required this.truncated});

  int count;

  /// Окно предпросмотра усечено: показывать надо «≥ N» (ТЗ §18 п. 16).
  bool truncated;

  List<Object?> _toList() {
    return <Object?>[count, truncated];
  }

  Object encode() {
    return _toList();
  }

  static PreviewDto decode(Object result) {
    result as List<Object?>;
    return PreviewDto(count: result[0]! as int, truncated: result[1]! as bool);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreviewDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(count, other.count) &&
        _deepEquals(truncated, other.truncated);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PreviewDto(count: $count, truncated: $truncated)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is SetupStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is RuleDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PatternCheckResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is SaveRuleResult) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is JournalItemDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is JournalPageDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is SummaryDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PreviewDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return SetupStatus.decode(readValue(buffer)!);
      case 130:
        return RuleDto.decode(readValue(buffer)!);
      case 131:
        return PatternCheckResult.decode(readValue(buffer)!);
      case 132:
        return SaveRuleResult.decode(readValue(buffer)!);
      case 133:
        return JournalItemDto.decode(readValue(buffer)!);
      case 134:
        return JournalPageDto.decode(readValue(buffer)!);
      case 135:
        return SummaryDto.decode(readValue(buffer)!);
      case 136:
        return PreviewDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class StatusApi {
  /// Constructor for [StatusApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  StatusApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<SetupStatus> status() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.StatusApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as SetupStatus;
  }

  /// Открывает системный диалог запроса роли. Возвращает false, если роль недоступна.
  Future<bool> requestRole() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.StatusApi.requestRole$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> openAppSettings() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.StatusApi.openAppSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

class RulesApi {
  /// Constructor for [RulesApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RulesApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
          ? '.$messageChannelSuffix'
          : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<RuleDto>> list() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.RulesApi.list$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<RuleDto>();
  }

  Future<SaveRuleResult> save(
    int? id,
    String title,
    String targetType,
    String matchType,
    String pattern,
    String action,
    bool enabled,
    String? regexField,
    bool? translitVariants,
    String? comment,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.RulesApi.save$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel
        .send(<Object?>[
          id,
          title,
          targetType,
          matchType,
          pattern,
          action,
          enabled,
          regexField,
          translitVariants,
          comment,
        ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as SaveRuleResult;
  }

  Future<void> setEnabled(int id, bool enabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.RulesApi.setEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id, enabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> delete(int id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.RulesApi.delete$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Переупорядочивание одной операцией: перенумерация идёт в одной транзакции.
  Future<void> reorder(List<int> idsInOrder) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.RulesApi.reorder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[idsInOrder],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<PatternCheckResult> checkPattern(
    String targetType,
    String matchType,
    String pattern,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.RulesApi.checkPattern$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[targetType, matchType, pattern],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PatternCheckResult;
  }

  Future<PreviewDto> preview(
    String targetType,
    String matchType,
    String pattern,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.RulesApi.preview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[targetType, matchType, pattern],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PreviewDto;
  }
}

class JournalApi {
  /// Constructor for [JournalApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  JournalApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<JournalPageDto> page(int? beforeTime, int? beforeId, int limit) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.JournalApi.page$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[beforeTime, beforeId, limit],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as JournalPageDto;
  }

  Future<SummaryDto> summary() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.JournalApi.summary$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as SummaryDto;
  }
}

class SettingsApi {
  /// Constructor for [SettingsApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SettingsApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<Map<String, String>> all() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.SettingsApi.all$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String, String>();
  }

  Future<void> put(String key, String value) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nope_call.SettingsApi.put$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
