// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.mist3s.nopecall.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NopeCallApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Состояние настройки. `blockingActive` намеренно отдельно от `hasRole`:
 * без роли сервис не вызывается вообще, и обещать «блокировка активна» нельзя (ТЗ §18 п. 2).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SetupStatus (
  val hasRole: Boolean,
  val hasCallLog: Boolean,
  val hasContacts: Boolean,
  val hasNotifications: Boolean,
  val blockingEnabled: Boolean,
  val blockingActive: Boolean,
  val enabledRuleCount: Long,
  /**
   * Коды проблем: NO_ROLE, DISABLED_BY_USER, NO_RULES, NO_CALL_LOG, NO_CONTACTS,
   * NO_NOTIFICATIONS. Строками, а не перечислением, чтобы добавление кода не ломало мост.
   */
  val problems: List<String>,
  val lastScreeningAt: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetupStatus {
      val hasRole = pigeonVar_list[0] as Boolean
      val hasCallLog = pigeonVar_list[1] as Boolean
      val hasContacts = pigeonVar_list[2] as Boolean
      val hasNotifications = pigeonVar_list[3] as Boolean
      val blockingEnabled = pigeonVar_list[4] as Boolean
      val blockingActive = pigeonVar_list[5] as Boolean
      val enabledRuleCount = pigeonVar_list[6] as Long
      val problems = pigeonVar_list[7] as List<String>
      val lastScreeningAt = pigeonVar_list[8] as Long?
      return SetupStatus(hasRole, hasCallLog, hasContacts, hasNotifications, blockingEnabled, blockingActive, enabledRuleCount, problems, lastScreeningAt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      hasRole,
      hasCallLog,
      hasContacts,
      hasNotifications,
      blockingEnabled,
      blockingActive,
      enabledRuleCount,
      problems,
      lastScreeningAt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SetupStatus
    return NopeCallApiPigeonUtils.deepEquals(this.hasRole, other.hasRole) && NopeCallApiPigeonUtils.deepEquals(this.hasCallLog, other.hasCallLog) && NopeCallApiPigeonUtils.deepEquals(this.hasContacts, other.hasContacts) && NopeCallApiPigeonUtils.deepEquals(this.hasNotifications, other.hasNotifications) && NopeCallApiPigeonUtils.deepEquals(this.blockingEnabled, other.blockingEnabled) && NopeCallApiPigeonUtils.deepEquals(this.blockingActive, other.blockingActive) && NopeCallApiPigeonUtils.deepEquals(this.enabledRuleCount, other.enabledRuleCount) && NopeCallApiPigeonUtils.deepEquals(this.problems, other.problems) && NopeCallApiPigeonUtils.deepEquals(this.lastScreeningAt, other.lastScreeningAt)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.hasRole)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.hasCallLog)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.hasContacts)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.hasNotifications)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.blockingEnabled)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.blockingActive)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.enabledRuleCount)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.problems)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.lastScreeningAt)
    return result
  }
  override fun toString(): String {
    return "SetupStatus(hasRole=$hasRole, hasCallLog=$hasCallLog, hasContacts=$hasContacts, hasNotifications=$hasNotifications, blockingEnabled=$blockingEnabled, blockingActive=$blockingActive, enabledRuleCount=$enabledRuleCount, problems=$problems, lastScreeningAt=$lastScreeningAt)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RuleDto (
  val id: Long,
  val title: String,
  val targetType: String,
  val matchType: String,
  /** Как ввёл пользователь — это и показывается ему. */
  val pattern: String,
  /** Канонизированный вид: по нему идёт сопоставление. Полезно показать в отладке. */
  val patternCanonical: String,
  val action: String,
  val orderIndex: Long,
  val isEnabled: Boolean,
  val translitVariants: Boolean,
  val matchCount: Long,
  val regexField: String? = null,
  val comment: String? = null,
  val lastMatchedAt: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RuleDto {
      val id = pigeonVar_list[0] as Long
      val title = pigeonVar_list[1] as String
      val targetType = pigeonVar_list[2] as String
      val matchType = pigeonVar_list[3] as String
      val pattern = pigeonVar_list[4] as String
      val patternCanonical = pigeonVar_list[5] as String
      val action = pigeonVar_list[6] as String
      val orderIndex = pigeonVar_list[7] as Long
      val isEnabled = pigeonVar_list[8] as Boolean
      val translitVariants = pigeonVar_list[9] as Boolean
      val matchCount = pigeonVar_list[10] as Long
      val regexField = pigeonVar_list[11] as String?
      val comment = pigeonVar_list[12] as String?
      val lastMatchedAt = pigeonVar_list[13] as Long?
      return RuleDto(id, title, targetType, matchType, pattern, patternCanonical, action, orderIndex, isEnabled, translitVariants, matchCount, regexField, comment, lastMatchedAt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      targetType,
      matchType,
      pattern,
      patternCanonical,
      action,
      orderIndex,
      isEnabled,
      translitVariants,
      matchCount,
      regexField,
      comment,
      lastMatchedAt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RuleDto
    return NopeCallApiPigeonUtils.deepEquals(this.id, other.id) && NopeCallApiPigeonUtils.deepEquals(this.title, other.title) && NopeCallApiPigeonUtils.deepEquals(this.targetType, other.targetType) && NopeCallApiPigeonUtils.deepEquals(this.matchType, other.matchType) && NopeCallApiPigeonUtils.deepEquals(this.pattern, other.pattern) && NopeCallApiPigeonUtils.deepEquals(this.patternCanonical, other.patternCanonical) && NopeCallApiPigeonUtils.deepEquals(this.action, other.action) && NopeCallApiPigeonUtils.deepEquals(this.orderIndex, other.orderIndex) && NopeCallApiPigeonUtils.deepEquals(this.isEnabled, other.isEnabled) && NopeCallApiPigeonUtils.deepEquals(this.translitVariants, other.translitVariants) && NopeCallApiPigeonUtils.deepEquals(this.matchCount, other.matchCount) && NopeCallApiPigeonUtils.deepEquals(this.regexField, other.regexField) && NopeCallApiPigeonUtils.deepEquals(this.comment, other.comment) && NopeCallApiPigeonUtils.deepEquals(this.lastMatchedAt, other.lastMatchedAt)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.id)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.title)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.targetType)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.matchType)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.pattern)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.patternCanonical)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.action)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.orderIndex)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.isEnabled)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.translitVariants)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.matchCount)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.regexField)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.comment)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.lastMatchedAt)
    return result
  }
  override fun toString(): String {
    return "RuleDto(id=$id, title=$title, targetType=$targetType, matchType=$matchType, pattern=$pattern, patternCanonical=$patternCanonical, action=$action, orderIndex=$orderIndex, isEnabled=$isEnabled, translitVariants=$translitVariants, matchCount=$matchCount, regexField=$regexField, comment=$comment, lastMatchedAt=$lastMatchedAt)"
  }
}

/**
 * Результат проверки шаблона в редакторе.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PatternCheckResult (
  val valid: Boolean,
  val canonical: String,
  /**
   * Что именно правило будет искать. Показывается пользователю: непрозрачное нечёткое
   * сравнение недопустимо, ложное срабатывание — пропущенный звонок от врача (ТЗ §6.3.2).
   */
  val variants: List<String>,
  val variantsTruncated: Boolean,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PatternCheckResult {
      val valid = pigeonVar_list[0] as Boolean
      val canonical = pigeonVar_list[1] as String
      val variants = pigeonVar_list[2] as List<String>
      val variantsTruncated = pigeonVar_list[3] as Boolean
      val error = pigeonVar_list[4] as String?
      return PatternCheckResult(valid, canonical, variants, variantsTruncated, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      valid,
      canonical,
      variants,
      variantsTruncated,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PatternCheckResult
    return NopeCallApiPigeonUtils.deepEquals(this.valid, other.valid) && NopeCallApiPigeonUtils.deepEquals(this.canonical, other.canonical) && NopeCallApiPigeonUtils.deepEquals(this.variants, other.variants) && NopeCallApiPigeonUtils.deepEquals(this.variantsTruncated, other.variantsTruncated) && NopeCallApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.valid)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.canonical)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.variants)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.variantsTruncated)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "PatternCheckResult(valid=$valid, canonical=$canonical, variants=$variants, variantsTruncated=$variantsTruncated, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SaveRuleResult (
  val saved: Boolean,
  val id: Long,
  val variants: List<String>,
  val variantsTruncated: Boolean,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SaveRuleResult {
      val saved = pigeonVar_list[0] as Boolean
      val id = pigeonVar_list[1] as Long
      val variants = pigeonVar_list[2] as List<String>
      val variantsTruncated = pigeonVar_list[3] as Boolean
      val error = pigeonVar_list[4] as String?
      return SaveRuleResult(saved, id, variants, variantsTruncated, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      saved,
      id,
      variants,
      variantsTruncated,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SaveRuleResult
    return NopeCallApiPigeonUtils.deepEquals(this.saved, other.saved) && NopeCallApiPigeonUtils.deepEquals(this.id, other.id) && NopeCallApiPigeonUtils.deepEquals(this.variants, other.variants) && NopeCallApiPigeonUtils.deepEquals(this.variantsTruncated, other.variantsTruncated) && NopeCallApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.saved)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.id)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.variants)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.variantsTruncated)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "SaveRuleResult(saved=$saved, id=$id, variants=$variants, variantsTruncated=$variantsTruncated, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class JournalItemDto (
  val id: Long,
  val occurredAt: Long,
  val rawNumber: String,
  val nameSource: String,
  val action: String,
  val reason: String,
  val latencyMs: Long,
  val blockedByUs: Boolean,
  val hadSignature: Boolean,
  val e164: String? = null,
  val nameRaw: String? = null,
  val matchedRuleId: Long? = null,
  val matchedRuleTitle: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JournalItemDto {
      val id = pigeonVar_list[0] as Long
      val occurredAt = pigeonVar_list[1] as Long
      val rawNumber = pigeonVar_list[2] as String
      val nameSource = pigeonVar_list[3] as String
      val action = pigeonVar_list[4] as String
      val reason = pigeonVar_list[5] as String
      val latencyMs = pigeonVar_list[6] as Long
      val blockedByUs = pigeonVar_list[7] as Boolean
      val hadSignature = pigeonVar_list[8] as Boolean
      val e164 = pigeonVar_list[9] as String?
      val nameRaw = pigeonVar_list[10] as String?
      val matchedRuleId = pigeonVar_list[11] as Long?
      val matchedRuleTitle = pigeonVar_list[12] as String?
      return JournalItemDto(id, occurredAt, rawNumber, nameSource, action, reason, latencyMs, blockedByUs, hadSignature, e164, nameRaw, matchedRuleId, matchedRuleTitle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      occurredAt,
      rawNumber,
      nameSource,
      action,
      reason,
      latencyMs,
      blockedByUs,
      hadSignature,
      e164,
      nameRaw,
      matchedRuleId,
      matchedRuleTitle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as JournalItemDto
    return NopeCallApiPigeonUtils.deepEquals(this.id, other.id) && NopeCallApiPigeonUtils.deepEquals(this.occurredAt, other.occurredAt) && NopeCallApiPigeonUtils.deepEquals(this.rawNumber, other.rawNumber) && NopeCallApiPigeonUtils.deepEquals(this.nameSource, other.nameSource) && NopeCallApiPigeonUtils.deepEquals(this.action, other.action) && NopeCallApiPigeonUtils.deepEquals(this.reason, other.reason) && NopeCallApiPigeonUtils.deepEquals(this.latencyMs, other.latencyMs) && NopeCallApiPigeonUtils.deepEquals(this.blockedByUs, other.blockedByUs) && NopeCallApiPigeonUtils.deepEquals(this.hadSignature, other.hadSignature) && NopeCallApiPigeonUtils.deepEquals(this.e164, other.e164) && NopeCallApiPigeonUtils.deepEquals(this.nameRaw, other.nameRaw) && NopeCallApiPigeonUtils.deepEquals(this.matchedRuleId, other.matchedRuleId) && NopeCallApiPigeonUtils.deepEquals(this.matchedRuleTitle, other.matchedRuleTitle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.id)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.occurredAt)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.rawNumber)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.nameSource)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.action)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.reason)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.latencyMs)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.blockedByUs)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.hadSignature)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.e164)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.nameRaw)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.matchedRuleId)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.matchedRuleTitle)
    return result
  }
  override fun toString(): String {
    return "JournalItemDto(id=$id, occurredAt=$occurredAt, rawNumber=$rawNumber, nameSource=$nameSource, action=$action, reason=$reason, latencyMs=$latencyMs, blockedByUs=$blockedByUs, hadSignature=$hadSignature, e164=$e164, nameRaw=$nameRaw, matchedRuleId=$matchedRuleId, matchedRuleTitle=$matchedRuleTitle)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class JournalPageDto (
  val items: List<JournalItemDto>,
  val hasMore: Boolean,
  /**
   * Курсор составной: метки времени в миллисекундах совпадают у соседних записей при
   * пакетной вставке, и курсор по одному полю пропускал бы строки (архитектура §7.3).
   */
  val nextBeforeTime: Long? = null,
  val nextBeforeId: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JournalPageDto {
      val items = pigeonVar_list[0] as List<JournalItemDto>
      val hasMore = pigeonVar_list[1] as Boolean
      val nextBeforeTime = pigeonVar_list[2] as Long?
      val nextBeforeId = pigeonVar_list[3] as Long?
      return JournalPageDto(items, hasMore, nextBeforeTime, nextBeforeId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      items,
      hasMore,
      nextBeforeTime,
      nextBeforeId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as JournalPageDto
    return NopeCallApiPigeonUtils.deepEquals(this.items, other.items) && NopeCallApiPigeonUtils.deepEquals(this.hasMore, other.hasMore) && NopeCallApiPigeonUtils.deepEquals(this.nextBeforeTime, other.nextBeforeTime) && NopeCallApiPigeonUtils.deepEquals(this.nextBeforeId, other.nextBeforeId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.items)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.hasMore)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.nextBeforeTime)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.nextBeforeId)
    return result
  }
  override fun toString(): String {
    return "JournalPageDto(items=$items, hasMore=$hasMore, nextBeforeTime=$nextBeforeTime, nextBeforeId=$nextBeforeId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SummaryDto (
  val blockedToday: Long,
  val totalEvents: Long,
  val withSignatureLast100: Long,
  val checkedLast100: Long,
  val lastEventAt: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SummaryDto {
      val blockedToday = pigeonVar_list[0] as Long
      val totalEvents = pigeonVar_list[1] as Long
      val withSignatureLast100 = pigeonVar_list[2] as Long
      val checkedLast100 = pigeonVar_list[3] as Long
      val lastEventAt = pigeonVar_list[4] as Long?
      return SummaryDto(blockedToday, totalEvents, withSignatureLast100, checkedLast100, lastEventAt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      blockedToday,
      totalEvents,
      withSignatureLast100,
      checkedLast100,
      lastEventAt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SummaryDto
    return NopeCallApiPigeonUtils.deepEquals(this.blockedToday, other.blockedToday) && NopeCallApiPigeonUtils.deepEquals(this.totalEvents, other.totalEvents) && NopeCallApiPigeonUtils.deepEquals(this.withSignatureLast100, other.withSignatureLast100) && NopeCallApiPigeonUtils.deepEquals(this.checkedLast100, other.checkedLast100) && NopeCallApiPigeonUtils.deepEquals(this.lastEventAt, other.lastEventAt)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.blockedToday)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.totalEvents)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.withSignatureLast100)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.checkedLast100)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.lastEventAt)
    return result
  }
  override fun toString(): String {
    return "SummaryDto(blockedToday=$blockedToday, totalEvents=$totalEvents, withSignatureLast100=$withSignatureLast100, checkedLast100=$checkedLast100, lastEventAt=$lastEventAt)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreviewDto (
  val count: Long,
  /** Окно предпросмотра усечено: показывать надо «≥ N» (ТЗ §18 п. 16). */
  val truncated: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreviewDto {
      val count = pigeonVar_list[0] as Long
      val truncated = pigeonVar_list[1] as Boolean
      return PreviewDto(count, truncated)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      count,
      truncated,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PreviewDto
    return NopeCallApiPigeonUtils.deepEquals(this.count, other.count) && NopeCallApiPigeonUtils.deepEquals(this.truncated, other.truncated)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.count)
    result = 31 * result + NopeCallApiPigeonUtils.deepHash(this.truncated)
    return result
  }
  override fun toString(): String {
    return "PreviewDto(count=$count, truncated=$truncated)"
  }
}
private open class NopeCallApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetupStatus.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RuleDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PatternCheckResult.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SaveRuleResult.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JournalItemDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JournalPageDto.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SummaryDto.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreviewDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SetupStatus -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RuleDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PatternCheckResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SaveRuleResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is JournalItemDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is JournalPageDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is SummaryDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PreviewDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface StatusApi {
  fun status(): SetupStatus
  /** Открывает системный диалог запроса роли. Возвращает false, если роль недоступна. */
  fun requestRole(callback: (Result<Boolean>) -> Unit)
  fun openAppSettings()

  companion object {
    /** The codec used by StatusApi. */
    val codec: MessageCodec<Any?> by lazy {
      NopeCallApiPigeonCodec()
    }
    /** Sets up an instance of `StatusApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: StatusApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.StatusApi.status$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.status())
            } catch (exception: Throwable) {
              NopeCallApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.StatusApi.requestRole$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestRole{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NopeCallApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.StatusApi.openAppSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAppSettings()
              listOf(null)
            } catch (exception: Throwable) {
              NopeCallApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RulesApi {
  fun list(callback: (Result<List<RuleDto>>) -> Unit)
  fun save(id: Long?, title: String, targetType: String, matchType: String, pattern: String, action: String, enabled: Boolean, regexField: String?, translitVariants: Boolean?, comment: String?, callback: (Result<SaveRuleResult>) -> Unit)
  fun setEnabled(id: Long, enabled: Boolean, callback: (Result<Unit>) -> Unit)
  fun delete(id: Long, callback: (Result<Unit>) -> Unit)
  /** Переупорядочивание одной операцией: перенумерация идёт в одной транзакции. */
  fun reorder(idsInOrder: List<Long>, callback: (Result<Unit>) -> Unit)
  fun checkPattern(targetType: String, matchType: String, pattern: String): PatternCheckResult
  fun preview(targetType: String, matchType: String, pattern: String, callback: (Result<PreviewDto>) -> Unit)

  companion object {
    /** The codec used by RulesApi. */
    val codec: MessageCodec<Any?> by lazy {
      NopeCallApiPigeonCodec()
    }
    /** Sets up an instance of `RulesApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RulesApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.RulesApi.list$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.list{ result: Result<List<RuleDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NopeCallApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.RulesApi.save$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long?
            val titleArg = args[1] as String
            val targetTypeArg = args[2] as String
            val matchTypeArg = args[3] as String
            val patternArg = args[4] as String
            val actionArg = args[5] as String
            val enabledArg = args[6] as Boolean
            val regexFieldArg = args[7] as String?
            val translitVariantsArg = args[8] as Boolean?
            val commentArg = args[9] as String?
            api.save(idArg, titleArg, targetTypeArg, matchTypeArg, patternArg, actionArg, enabledArg, regexFieldArg, translitVariantsArg, commentArg) { result: Result<SaveRuleResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NopeCallApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.RulesApi.setEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val enabledArg = args[1] as Boolean
            api.setEnabled(idArg, enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NopeCallApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.RulesApi.delete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            api.delete(idArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NopeCallApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.RulesApi.reorder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idsInOrderArg = args[0] as List<Long>
            api.reorder(idsInOrderArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NopeCallApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.RulesApi.checkPattern$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val targetTypeArg = args[0] as String
            val matchTypeArg = args[1] as String
            val patternArg = args[2] as String
            val wrapped: List<Any?> = try {
              listOf(api.checkPattern(targetTypeArg, matchTypeArg, patternArg))
            } catch (exception: Throwable) {
              NopeCallApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.RulesApi.preview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val targetTypeArg = args[0] as String
            val matchTypeArg = args[1] as String
            val patternArg = args[2] as String
            api.preview(targetTypeArg, matchTypeArg, patternArg) { result: Result<PreviewDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NopeCallApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface JournalApi {
  fun page(beforeTime: Long?, beforeId: Long?, limit: Long, callback: (Result<JournalPageDto>) -> Unit)
  fun summary(callback: (Result<SummaryDto>) -> Unit)

  companion object {
    /** The codec used by JournalApi. */
    val codec: MessageCodec<Any?> by lazy {
      NopeCallApiPigeonCodec()
    }
    /** Sets up an instance of `JournalApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: JournalApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.JournalApi.page$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val beforeTimeArg = args[0] as Long?
            val beforeIdArg = args[1] as Long?
            val limitArg = args[2] as Long
            api.page(beforeTimeArg, beforeIdArg, limitArg) { result: Result<JournalPageDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NopeCallApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.JournalApi.summary$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.summary{ result: Result<SummaryDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NopeCallApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SettingsApi {
  fun all(callback: (Result<Map<String, String>>) -> Unit)
  fun put(key: String, value: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by SettingsApi. */
    val codec: MessageCodec<Any?> by lazy {
      NopeCallApiPigeonCodec()
    }
    /** Sets up an instance of `SettingsApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SettingsApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.SettingsApi.all$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.all{ result: Result<Map<String, String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NopeCallApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nope_call.SettingsApi.put$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            api.put(keyArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NopeCallApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NopeCallApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
